version: '3.7'
services:
    app:
        build:
            args:
                user: filehost
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - basedzone
        environment:
            APP_NAME: 'BasedZone'
            APP_DEBUG: 'true'
            APP_URL: 'http://localhost:22222'
            DB_CONNECTION: 'mysql'
            DB_HOST: db
            DB_DATABASE: basedzone
            DB_USERNAME: root
            DB_PASSWORD: '!QAZ!QAZ1qaz1qaz'
            BTC_ADDR: 'bc1q4lkjj43sq43pt4hcwpcdmpa6samc34f3c4tk4m'
            DOGE_ADDR: 'D7VLZgAhdUW92JTGA5k45f1L9d5hBVzUrF'

    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 22222:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - basedzone

    db:
      image: mariadb:10.5.5
      container_name: basedzone-db
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: basedzone
        MYSQL_ROOT_PASSWORD: '!QAZ!QAZ1qaz1qaz'
        SERVICE_TAGS: dev
        SERVICE_NAME: mariadb
      volumes:
        - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      networks:
        - basedzone

networks:
    basedzone:
        driver: bridge
